$(document).ready(function() {
    //Change language to show
    $('#languages').on('change', function() {
        let lan = $(this).val();
        if (lan == 'en' || lan == 'en-AU' || lan == 'en-CA' || lan == 'en-IN' || lan == 'en-NZ' || lan == 'en-ZA' || lan == 'en-GB' || lan == 'en-US') {
            $('.stylebtn:eq(0)').text('GO!');
            $('.stylebtn').slice(1).text('Enter');
            $('.mobile p:eq(0)').text('Watch 6000+ TV Channels...');
            $('.mobile p:eq(1)').text('Watch Movies, Series, Animes...');
            $('.mobile p:eq(2)').text('Listen 28000+ Radio Stations...');
            $('.mobile p:eq(3)').text('Reading More Than 100000+ Books...');
            $('.mobile p:eq(4)').text('Reading Lots of Manga Books...');
            $('.mobile p:eq(5)').text('Listen to The World Music...');
            $('.mobile p:eq(6)').text('Constructing until version 9.0.0');
            $('.mobile p:eq(7)').text('Video porno...');
            $('h2').text('Select');
            $('#selectform input:eq(0)').next().text('Countries');
            $('#selectform input:eq(1)').next().text('Languages');
            $('#selectform input:eq(2)').next().text('Category');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Sensitive Content');
            $('#mySidenav a:eq(1)').find('span').text('Languages');
            $('#mySidenav a:eq(2)').find('span').text('Version');
        } else if (lan == 'id') {
            $('.stylebtn').text('Memasuki');
            $('.mobile p:eq(0)').text('Tonton 6000+ Saluran TV...');
            $('.mobile p:eq(1)').text('Tonton Film, Serial, Anime...');
            $('.mobile p:eq(2)').text('Dengarkan 28000+ Stasiun Radio...');
            $('.mobile p:eq(3)').text('Membaca Lebih Dari 100000+ Buku...');
            $('.mobile p:eq(4)').text('Membaca Banyak Buku Manga...');
            $('.mobile p:eq(5)').text('Dengarkan Musik Dunia...');
            $('.mobile p:eq(6)').text('Membangun hingga versi 9.0.0');
            $('.mobile p:eq(7)').text('วิดีโอโป๊...');
            $('h2').text('Pilih');
            $('#selectform input:eq(0)').next().text('negara');
            $('#selectform input:eq(1)').next().text('Bahasa');
            $('#selectform input:eq(2)').next().text('Kategori');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Konten Sensitif');
            $('#mySidenav a:eq(1)').find('span').text('Bahasa');
            $('#mySidenav a:eq(2)').find('span').text('Versi: kapan');
        } else if (lan == 'th') {
            $('.stylebtn').text('เข้า');
            $('.mobile p:eq(0)').text('ดูทีวีช่อง 6000+...');
            $('.mobile p:eq(1)').text('ดูหนัง ซีรี่ย์ อนิเมะ...');
            $('.mobile p:eq(2)').text('ฟังสถานีวิทยุกว่า 28,000 แห่ง...');
            $('.mobile p:eq(3)').text('อ่านหนังสือมากกว่า 100,000 เล่ม...');
            $('.mobile p:eq(4)').text('อ่านหนังสือการ์ตูนหลายเล่ม...');
            $('.mobile p:eq(5)').text('ฟังเพลงสากล...');
            $('.mobile p:eq(6)').text('กำลังสร้างจนถึงเวอร์ชัน 9.0.0');
            $('.mobile p:eq(7)').text('วิดีโอโป๊...');
            $('h2').text('เลือก');
            $('#selectform input:eq(0)').next().text('ประเทศ');
            $('#selectform input:eq(1)').next().text('ภาษา');
            $('#selectform input:eq(2)').next().text('หมวดหมู่');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('เนื้อหาละเอียดอ่อน');
            $('#mySidenav a:eq(1)').find('span').text('ภาษา');
            $('#mySidenav a:eq(2)').find('span').text('เวอร์ชั่น');
        } else if (lan == 'it' || lan == 'it-IT' || lan == 'it-CH') {
            $('.stylebtn').text('accedere');
            $('.mobile p:eq(0)').text('Guarda oltre 6000 canali TV...');
            $('.mobile p:eq(1)').text('Guarda film, serie, anime...');
            $('.mobile p:eq(2)').text('Ascolta più di 28000 stazioni radio...');
            $('.mobile p:eq(3)').text('Leggendo più di 100000+ libri...');
            $('.mobile p:eq(4)').text('Leggendo molti libri di manga...');
            $('.mobile p:eq(5)').text('Ascolta The World Music...');
            $('.mobile p:eq(6)').text('Costruzione fino alla versione 9.0.0');
            $('.mobile p:eq(7)').text('Video porno...');
            $('h2').text('Selezionare');
            $('#selectform input:eq(0)').next().text('Paesi');
            $('#selectform input:eq(1)').next().text('Le lingue');
            $('#selectform input:eq(2)').next().text('Categoria');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Contenuti sensibili');
            $('#mySidenav a:eq(1)').find('span').text('Le lingue');
            $('#mySidenav a:eq(2)').find('span').text('Versione');
        } else if (lan == 'ru') {
            $('.stylebtn').text('Входить');
            $('.mobile p:eq(0)').text('Смотрите 6000+ телеканалов ...');
            $('.mobile p:eq(1)').text('Смотрите фильмы, сериалы, аниме ...');
            $('.mobile p:eq(2)').text('Слушайте 28000+ радиостанций ...');
            $('.mobile p:eq(3)').text('Чтение более 100000+ книг ...');
            $('.mobile p:eq(4)').text('Читаю много книг манги ...');
            $('.mobile p:eq(5)').text('Слушайте музыку мира ...');
            $('.mobile p:eq(6)').text('Сборка до версии 9.0.0');
            $('.mobile p:eq(7)').text('Порно видео ...');
            $('h2').text('Выбирать');
            $('#selectform input:eq(0)').next().text('Страны');
            $('#selectform input:eq(1)').next().text('Языки');
            $('#selectform input:eq(2)').next().text('Категория');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Деликатный контент');
            $('#mySidenav a:eq(1)').find('span').text('Языки');
            $('#mySidenav a:eq(2)').find('span').text('Версия');
        } else if (lan == 'pt' || lan == 'pt-BR' || lan == 'pt-PT') {
            $('.stylebtn').text('Digitar');
            $('.mobile p:eq(0)').text('Assistir mais de 6.000 canais de TV ...');
            $('.mobile p:eq(1)').text('Assistir filmes, séries, animes ...');
            $('.mobile p:eq(2)').text('Ouça mais de 28.000 estações de rádio ...');
            $('.mobile p:eq(3)').text('Lendo mais de 100.000 livros ...');
            $('.mobile p:eq(4)').text('Lendo muitos livros de mangá ...');
            $('.mobile p:eq(5)').text('Ouça The World Music ...');
            $('.mobile p:eq(6)').text('Construindo até a versão 9.0.0');
            $('.mobile p:eq(7)').text('Vídeos pornôs ...');
            $('h2').text('Selecione');
            $('#selectform input:eq(0)').next().text('Países');
            $('#selectform input:eq(1)').next().text('línguas');
            $('#selectform input:eq(2)').next().text('Categoria');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Conteúdo Sensível');
            $('#mySidenav a:eq(1)').find('span').text('línguas');
            $('#mySidenav a:eq(2)').find('span').text('Versão');
        } else if (lan == 'es' || lan == 'es-AR' || lan == 'es-419' || lan == 'es-MX' || lan == 'es-ES' || lan == 'es-US') {
            $('.stylebtn').text('Ingresar');
            $('.mobile p:eq(0)').text('Mira más de 6000 canales de televisión ...');
            $('.mobile p:eq(1)').text('Ver películas, series, animes ...');
            $('.mobile p:eq(2)').text('Escuche más de 28000 estaciones de radio ...');
            $('.mobile p:eq(3)').text('Leyendo más de 100000+ libros ...');
            $('.mobile p:eq(4)').text('Leyendo muchos libros de manga ...');
            $('.mobile p:eq(5)').text('Escuche The World Music ...');
            $('.mobile p:eq(6)').text('Construyendo hasta la versión 9.0.0');
            $('.mobile p:eq(7)').text('Vídeos porno ...');
            $('h2').text('Seleccione');
            $('#selectform input:eq(0)').next().text('Países');
            $('#selectform input:eq(1)').next().text('Idiomas');
            $('#selectform input:eq(2)').next().text('Categoría');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Contenido sensible');
            $('#mySidenav a:eq(1)').find('span').text('Idiomas');
            $('#mySidenav a:eq(2)').find('span').text('Versión');
        } else if (lan == 'az') {
            $('.stylebtn').text('Daxil edin');
            $('.mobile p:eq(0)').text('6000 -dən çox TV kanalına baxın ...');
            $('.mobile p:eq(1)').text('Filmlərə, Seriyalara, Cizgi filmlərinə baxın ...');
            $('.mobile p:eq(2)').text('28000+ Radio Stansiyasına qulaq asın ...');
            $('.mobile p:eq(3)').text('100000 -dən çox kitab oxumaq ...');
            $('.mobile p:eq(4)').text('Çox Manga Kitabları Oxuyur ...');
            $('.mobile p:eq(5)').text('Dünya musiqisini dinləyin ...');
            $('.mobile p:eq(6)').text('9.0.0 versiyasına qədər tikinti');
            $('.mobile p:eq(7)').text('Porno Videolar..');
            $('h2').text('Seçin');
            $('#selectform input:eq(0)').next().text('Ölkələr');
            $('#selectform input:eq(1)').next().text('Dillər');
            $('#selectform input:eq(2)').next().text('Kateqoriya');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Həssas Məzmun');
            $('#mySidenav a:eq(1)').find('span').text('Dillər');
            $('#mySidenav a:eq(2)').find('span').text('Versiya');
        } else if (lan == 'hy') {
            $('.stylebtn').text('Մուտքագրեք');
            $('.mobile p:eq(0)').text('Դիտեք 6000+ հեռուստաալիք ...');
            $('.mobile p:eq(1)').text('Դիտեք ֆիլմեր, սերիալներ, անիմեներ ...');
            $('.mobile p:eq(2)').text('Լսեք 28000+ ռադիոկայան ...');
            $('.mobile p:eq(3)').text('Կարդում է ավելի քան 100000+ գիրք ...');
            $('.mobile p:eq(4)').text('Մանգայի շատ գրքեր կարդալը ...');
            $('.mobile p:eq(5)').text('Լսեք համաշխարհային երաժշտությունը ...');
            $('.mobile p:eq(6)').text('Կառուցող մինչև 9.0.0 տարբերակ');
            $('.mobile p:eq(7)').text('Պոռնո տեսանյութեր ...');
            $('h2').text('Ընտրել');
            $('#selectform input:eq(0)').next().text('Երկրներ');
            $('#selectform input:eq(1)').next().text('Լեզուներ');
            $('#selectform input:eq(2)').next().text('Կատեգորիա');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Sգայուն բովանդակություն');
            $('#mySidenav a:eq(1)').find('span').text('Լեզուներ');
            $('#mySidenav a:eq(2)').find('span').text('Տարբերակ');
        } else if (lan == 'de' || lan == 'de-AT' || lan == 'de-DE' || lan == 'de-LI' || lan == 'de-CH') {
            $('.stylebtn').text('Eintreten');
            $('.mobile p:eq(0)').text('Mehr als 6000 TV-Kanäle ansehen...');
            $('.mobile p:eq(1)').text('Filme, Serien, Animes ansehen...');
            $('.mobile p:eq(2)').text('Mehr als 28000 Radiosender anhören...');
            $('.mobile p:eq(3)').text('Mehr als 100.000+ Bücher lesen...');
            $('.mobile p:eq(4)').text('Viele Manga-Bücher lesen...');
            $('.mobile p:eq(5)').text('Weltmusik hören...');
            $('.mobile p:eq(6)').text('Konstruieren bis Version 9.0.0');
            $('.mobile p:eq(7)').text('Pornovideos...');
            $('h2').text('Auswählen');
            $('#selectform input:eq(0)').next().text('Land');
            $('#selectform input:eq(1)').next().text('Sprachen');
            $('#selectform input:eq(2)').next().text('Kategorie');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Sensible Inhalte');
            $('#mySidenav a:eq(1)').find('span').text('Sprachen');
            $('#mySidenav a:eq(2)').find('span').text('Ausführung');
        } else if (lan == 'fr' || lan == 'fr-CA' || lan == 'fr-FR' || lan == 'fr-CH') {
            $('.stylebtn').text('Entrer');
            $('.mobile p:eq(0)').text('Regardez plus de 6000 chaînes de télévision...');
            $('.mobile p:eq(1)').text('Regardez des films, séries, animes...');
            $('.mobile p:eq(2)').text('Écoutez plus de 28 000 stations de radio...');
            $('.mobile p:eq(3)').text('Lire plus de 100000+ livres...');
            $('.mobile p:eq(4)').text('Lire beaucoup de mangas...');
            $('.mobile p:eq(5)').text('Écoutez la musique du monde...');
            $('.mobile p:eq(6)').text('Construire jusqu\'à la version 9.0.0');
            $('.mobile p:eq(7)').text('Vidéos porno...');
            $('h2').text('Sélectionner');
            $('#selectform input:eq(0)').next().text('Des pays');
            $('#selectform input:eq(1)').next().text('Langages');
            $('#selectform input:eq(2)').next().text('Catégorie');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Contenu sensible');
            $('#mySidenav a:eq(1)').find('span').text('Langages');
            $('#mySidenav a:eq(2)').find('span').text('Version');
        } else if (lan == 'ar') {
            $('.stylebtn').text('يدخل');
            $('.mobile p:eq(0)').text('شاهد أكثر من 6000 قناة تلفزيونية ...');
            $('.mobile p:eq(1)').text('مشاهدة الافلام والمسلسلات والرسوم المتحركة ...');
            $('.mobile p:eq(2)').text('الاستماع 28000+ محطات الراديو ...');
            $('.mobile p:eq(3)').text('قراءة أكثر من 100000+ كتاب ...');
            $('.mobile p:eq(4)').text('قراءة الكثير من كتب المانجا ...');
            $('.mobile p:eq(5)').text('الاستماع إلى الموسيقى العالمية ...');
            $('.mobile p:eq(6)').text('جاري الإنشاء حتى الإصدار 9.0.0');
            $('.mobile p:eq(7)').text('أشرطة الفيديو الإباحية ...');
            $('h2').text('يختار');
            $('#selectform input:eq(0)').next().text('بلدان');
            $('#selectform input:eq(1)').next().text('اللغات');
            $('#selectform input:eq(2)').next().text('فئة');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('المحتوى الحساس');
            $('#mySidenav a:eq(1)').find('span').text('اللغات');
            $('#mySidenav a:eq(2)').find('span').text('إصدار');
        } else if (lan == 'sq') {
            $('.stylebtn').text('Hyni');
            $('.mobile p:eq(0)').text('Shikoni 6000+ kanale televizive ...');
            $('.mobile p:eq(1)').text('Shikoni filma, seri, anime ...');
            $('.mobile p:eq(2)').text('Dëgjoni 28000+ Stacione Radio ...');
            $('.mobile p:eq(3)').text('Leximi i më shumë se 100000+ librave ...');
            $('.mobile p:eq(4)').text('Duke lexuar shumë libra Manga ...');
            $('.mobile p:eq(5)').text('Dëgjoni Muzikën Botërore ...');
            $('.mobile p:eq(6)').text('Ndërtimi deri në versionin 9.0.0');
            $('.mobile p:eq(7)').text('Video pornografike ...');
            $('h2').text('Zgjidhni');
            $('#selectform input:eq(0)').next().text('Vendet');
            $('#selectform input:eq(1)').next().text('Gjuhët');
            $('#selectform input:eq(2)').next().text('Kategoria');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('Përmbajtje e ndjeshme');
            $('#mySidenav a:eq(1)').find('span').text('Gjuhët');
            $('#mySidenav a:eq(2)').find('span').text('Version');
        } else if (lan == 'am') {
            $('.stylebtn').text('ግባ');
            $('.mobile p:eq(0)').text('6000+ የቴሌቪዥን ጣቢያዎችን ይመልከቱ ...');
            $('.mobile p:eq(1)').text('ፊልሞችን ፣ ተከታታዮችን ፣ አኒሞችን ይመልከቱ ...');
            $('.mobile p:eq(2)').text('28000+ የሬዲዮ ጣቢያዎችን ያዳምጡ ...');
            $('.mobile p:eq(3)').text('ከ 100000+ በላይ መጽሐፍትን በማንበብ ...');
            $('.mobile p:eq(4)').text('ብዙ የማንጋ መጽሐፍትን በማንበብ ላይ ...');
            $('.mobile p:eq(5)').text('የአለም ሙዚቃን ያዳምጡ ...');
            $('.mobile p:eq(6)').text('እስከ ስሪት 9.0.0 ድረስ በመገንባት ላይ');
            $('.mobile p:eq(7)').text('የወሲብ ቪዲዮዎች ...');
            $('h2').text('ይምረጡ');
            $('#selectform input:eq(0)').next().text('አገሮች');
            $('#selectform input:eq(1)').next().text('ቋንቋዎች');
            $('#selectform input:eq(2)').next().text('ምድብ');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('ስሜታዊ ይዘት');
            $('#mySidenav a:eq(1)').find('span').text('ቋንቋዎች');
            $('#mySidenav a:eq(2)').find('span').text('ስሪት');
        } else if (lan == 'zh' || lan == 'zh-CN') {
            $('.stylebtn').text('进入');
            $('.mobile p:eq(0)').text('观看6000多个电视直播台......');
            $('.mobile p:eq(1)').text('观看电影，电视剧，动漫......');
            $('.mobile p:eq(2)').text('收听28000多个电台频道......');
            $('.mobile p:eq(3)').text('阅读超过10本图书...');
            $('.mobile p:eq(4)').text('浏览海量漫画...');
            $('.mobile p:eq(5)').text('聆听世界的音乐...');
            $('.mobile p:eq(6)').text('建设中直到9.0.0版本');
            $('.mobile p:eq(7)').text('色情视频...');
            $('h2').text('选择');
            $('#selectform input:eq(0)').next().text('国家');
            $('#selectform input:eq(1)').next().text('语言');
            $('#selectform input:eq(2)').next().text('分类');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('敏感内容');
            $('#mySidenav a:eq(1)').find('span').text('语言');
            $('#mySidenav a:eq(2)').find('span').text('版本');
        } else if (lan == 'zh-HK' || lan == 'zh-TW') {
            $('.stylebtn').text('進入');
            $('.mobile p:eq(0)').text('觀看 6000 多個電視頻道...');
            $('.mobile p:eq(1)').text('看電影、電視劇、動漫……');
            $('.mobile p:eq(2)').text('收聽 28000 多個廣播電台...');
            $('.mobile p:eq(3)').text('閱讀超過100000本書...');
            $('.mobile p:eq(4)').text('瀏覽大量漫畫書...');
            $('.mobile p:eq(5)').text('聽聽世界的音樂...');
            $('.mobile p:eq(6)').text('建設中直到9.0.0版本');
            $('.mobile p:eq(7)').text('色情影片...');
            $('h2').text('选择');
            $('#selectform input:eq(0)').next().text('國家');
            $('#selectform input:eq(1)').next().text('語言');
            $('#selectform input:eq(2)').next().text('分類');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('敏感內容');
            $('#mySidenav a:eq(1)').find('span').text('語言');
            $('#mySidenav a:eq(2)').find('span').text('版本');
        } else if (lan == 'af') {
            $('.stylebtn').text('Tik in');
            $('.mobile p:eq(0)').text('Kyk na 6000+ TV -kanale ...');
            $('.mobile p:eq(1)').text('Kyk films, reekse, anime ...');
            $('.mobile p:eq(2)').text('Luister na 28000+ radiostasies ...');
            $('.mobile p:eq(3)').text('Lees meer as 100000+ boeke ...');
            $('.mobile p:eq(4)').text('Lees baie mangaboeke ...');
            $('.mobile p:eq(5)').text('Luister na The World Music ...');
            $('.mobile p:eq(6)').text('Konstrueer tot weergawe 9.0.0');
            $('.mobile p:eq(7)').text('Porno video\'s ...');
            $('h2').text('kies');
            $('#selectform input:eq(0)').next().text('land');
            $('#selectform input:eq(1)').next().text('Taal');
            $('#selectform input:eq(2)').next().text('kategorie');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('sensitiewe inhoud');
            $('#mySidenav a:eq(1)').find('span').text('Taal');
            $('#mySidenav a:eq(2)').find('span').text('weergawe');
        } else if (lan == 'ja') {
            $('.stylebtn').text('入力');
            $('.mobile p:eq(0)').text('6000以上のテレビチャンネルを見る...');
            $('.mobile p:eq(1)').text('映画、シリーズ、アニメを見る...');
            $('.mobile p:eq(2)').text('28000以上のラジオ局を聞く...');
            $('.mobile p:eq(3)').text('100000冊以上の本を読む...');
            $('.mobile p:eq(4)').text('たくさんのマンガ本を読んで...');
            $('.mobile p:eq(5)').text('ワールドミュージックを聴く...');
            $('.mobile p:eq(6)').text('バージョン9.0.0まで構築中');
            $('.mobile p:eq(7)').text('ポルノビデオ...');
            $('h2').text('選択する');
            $('#selectform input:eq(0)').next().text('国');
            $('#selectform input:eq(1)').next().text('言語');
            $('#selectform input:eq(2)').next().text('カテゴリー');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('デリケートなコンテンツ');
            $('#mySidenav a:eq(1)').find('span').text('言語');
            $('#mySidenav a:eq(2)').find('span').text('バージョン');
        } else if (lan == 'hi') {
            $('.stylebtn').text('प्रवेश करना');
            $('.mobile p:eq(0)').text('6000+ टीवी चैनल देखें...');
            $('.mobile p:eq(1)').text('फिल्में, सीरीज, एनीमे देखें...');
            $('.mobile p:eq(2)').text('28000+ रेडियो स्टेशन सुनें...');
            $('.mobile p:eq(3)').text('१०००००+ से अधिक पुस्तकें पढ़ना...');
            $('.mobile p:eq(4)').text('बहुत सारी मंगा किताबें पढ़ना...');
            $('.mobile p:eq(5)').text('विश्व संगीत सुनें ...');
            $('.mobile p:eq(6)').text('संस्करण 9.0.0 . तक निर्माण');
            $('.mobile p:eq(7)').text('अश्लील वीडियो...');
            $('h2').text('चुनते हैं');
            $('#selectform input:eq(0)').next().text('देश');
            $('#selectform input:eq(1)').next().text('भाषा: हिन्दी');
            $('#selectform input:eq(2)').next().text('श्रेणी');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('संवेदनशील सामग्री');
            $('#mySidenav a:eq(1)').find('span').text('भाषा: हिन्दी');
            $('#mySidenav a:eq(2)').find('span').text('संस्करण');
        } else if (lan == 'ko') {
            $('.stylebtn').text('입력하다');
            $('.mobile p:eq(0)').text('6000개 이상의 TV 채널 시청...');
            $('.mobile p:eq(1)').text('영화, 시리즈, 애니메이션 감상...');
            $('.mobile p:eq(2)').text('28000개 이상의 라디오 방송국 듣기...');
            $('.mobile p:eq(3)').text('100000권 이상의 책 읽기...');
            $('.mobile p:eq(4)').text('만화책 많이 읽고...');
            $('.mobile p:eq(5)').text('월드뮤직을 듣다...');
            $('.mobile p:eq(6)').text('버전 9.0.0까지 구축 중');
            $('.mobile p:eq(7)').text('포르노 비디오...');
            $('h2').text('선택하다');
            $('#selectform input:eq(0)').next().text('국가');
            $('#selectform input:eq(1)').next().text('언어');
            $('#selectform input:eq(2)').next().text('श्रेणी');
            $('#mySidenav a:eq(0)').find('span:eq(0)').text('범주');
            $('#mySidenav a:eq(1)').find('span').text('언어');
            $('#mySidenav a:eq(2)').find('span').text('버전');
        }
    });
})